### ISSUE TITLE
1. Improved Task Management

### ISSUE THREAD

**Issue by manavkamdar27** [brianhhuynh38/slackpoint-v3#1]
Currently SlackPoint stores tasks all in one large list with no good way to filter them out. We believe that this can be solved via the introduction of 
- [x] **Task Tags** : String tags that are used as identifiers for each task. Each Task should be able to hold multiple string tags.
- [x] **Task Filtering** : These tags can be used to filter tasks  in order to improve organization in the bot, as it currently outputs very large lists of existing tasks.

**Comment by manavkamdar27** [comment]
Do you mean you want to categorise the tasks, based on user generated tags?
Does this have to be an additional parameter when a user creates a task?

**Comment by brianhhuynh38** [comment]
Yes, to clarify:

**Task Tags** should be represented by a set of strings that are used as labels for each of the tasks. These should be represented in `/create-task`, `edit-task`, `/view-tasks`, etc.. Essentially, any task that the user is able to create, view, or edit should be able to have their categorization tags visible. Of course, each task can have multiple labels.

This can be likened to the Labels used for GitHub issues that are essentially visual markers and is a way to differentiate GitHub Issues from each other due to the category that they fall into.

**Comment by brianhhuynh38** [comment]
I took a look at your implementation (as per your request) for the tags and it looks like it properly adds and edits the tags from the database. However there are a few things I'd like to note:

- Tags cannot be viewed yet in `/viewpending` and assumably `/viewcompleted`
- The tags do not auto-populate the input field in `/edit-task`
- The tags input field appears below the submit button in both create and edit. This isn't necessarily a bad thing, but it could be something worth noting provided we have the time.

The basics do seem to be complete though, so I'd like to expand on the tasks here:

- [ ] Add tags to `/viewpending`
- [ ] Add tags to `/viewcompleted`
- [ ] Have fields auto-populate if tags already exist (just in `/edit-task`)

I'll try to help out a bit with this as well.
