### ISSUE TITLE
2. Deeper Gamification - Character Creation and Progression Systems

### ISSUE THREAD

**Issue by brianhhuynh38** [brianhhuynh38/slackpoint-v3#2]
## Introduction

Currently, the SlackPoint system attempts to gamify task assignment and completion via awarding points to users that claim to have completed a task. While the quantification of task completion could help to motivate and incentivize task completion, we would like to build upon the foundation established by the previous team.

## Plans for This Iteration
We expect to establish a new system in which these points can be used in a risk-reward progression system. Our initial idea is to make this new system similar to that of a very simple Tabletop RPG where players will be able to use their points to strengthen their characters through the allocation of the points they earn through task completion. The specifics of this system still are not rigidly defined and can change as more ideas come to mind during development.

### Proposed Tasks
- [x] Brainstorm ideas to further and more accurately define what kind of game mechanics should be present in an environment not normally made for gaming. Slack is primarily a communications program which has minimal support for anything more advanced than text-based or RPG games. (#6)
- [x] Refactor database in order to account for new user data that has to be stored by the database (character statistics, inventory, etc.). (#16)
- [x] Implement character creation system that allows the user to customize their player and move set (#16)
- [x] Implement a progression system using the new character stats in order to let users get stronger through task completion (#17 ).

While these tasks have been defined above, they are still subject to change as the project develops and evolves during the course of this project. Discussions will be held below as to what potential changes could be made to the system.

**Comment by brianhhuynh38** [comment]
Documentation regarding the definition of the potential game mechanics is now shown via the [Game Design Task](#6) and is now present in the GitHub Wiki as well under the Game Design section.

**Comment by brianhhuynh38** [comment]
I have split this iteration into two separate iterations due to the sheer size of it compared to [Iteration 1](#1). This iteration now covers just the character creation and stats while the battle system has been moved over to [Iteration 3](#12).

**Comment by brianhhuynh38** [comment]
All functionality has been achieved for the progression system and character creation.
